### ISSUE TITLE
GPG keys can't decrypting the files

### ISSUE THREAD

**Issue by IAteNoodles** [wsldl-pg/ArchW-docs#48]
I have been using pass to store my passwords, but on wsl when I use the `pass show XYZ` I get `gpg: decryption failed: No secret key`

I have tried changing the perms, onwerships but nothing works, and I think this is an inherit drawback of wsl, I may be wrong. 

I to be sure, tried using this on a native linux machine and it worked.

I even created a new gpg key and used it to encrypt and decrypt a message, but I got the same error.

**Comment by sileshn** [comment]
pass works fine on wsl2. I tried it on debian, manjaro and archlinux.

**Comment by IAteNoodles** [comment]
> pass works fine on wsl2. I tried it on debian, manjaro and archlinux.

Are you able to enter your paraphrase?
Can you please tell me your setup in archlinux apart from pass what are the things are you using?

**Comment by sileshn** [comment]
Have you setup pinentry? If not, you will need to set it up to display the dialog to enter your paraphrase.

sudo pacman -S pinentry
echo 'export GPG_TTY=$(tty)' | tee -a /home/$USER/.bashrc
echo 'pinentry-program /usr/bin/pinentry-curses' | sudo tee -a ~/.gnupg/gpg-agent.conf
echo RELOADAGENT | gpg-connect-agent /bye

**Comment by IAteNoodles** [comment]
> Have you setup pinentry? If not, you will need to set it up to display the dialog to enter your paraphrase.
> 
> sudo pacman -S pinentry echo 'export GPG_TTY=$(tty)' | tee -a /home/$USER/.bashrc echo 'pinentry-program /usr/bin/pinentry-curses' | sudo tee -a ~/.gnupg/gpg-agent.conf echo RELOADAGENT | gpg-connect-agent /bye

I tried your way, but it didn't do anything, 
Tho I reinstalled the wsl and it worked.
